---
# Example: https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml
project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: false
  resources:
    - "/.nojekyll"
    - "/static/*"
  render:
    - "*.qmd"

execute:
  freeze: auto  # Re-compute previously generated computational output only in case their source file changes

website:
  title: "Toolkit"
  description: "Geocoug's Toolkit"
  favicon: /static/favicon.ico
  site-url: http://toolkit.goecoug.com
  page-navigation: true
  back-to-top-navigation: true
  repo-url: https://github.com/geocoug/toolkit
  repo-actions: [issue]
  search:
    location: navbar
    copy-button: true
  page-footer:
    left: "Caleb Grant, 2023"
    background: light
    right:
      - icon: github
        href: https://github.com/geocoug/toolkit
  navbar:
    title: false
    logo: /static/logo.svg
    collapse-below: lg
    left:
      - text: "Development"
        href: docs/development/index.qmd
      - text: "Resources"
        href: docs/resources/index.qmd
      - text: "Blog"
        href: docs/blog/index.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/c-grant/
      - icon: github
        href: https://github.com/geocoug

  sidebar:
    - id: development
      collapse-level: 2
      align: left
      style: "docked"
      contents:
        - docs/development/index.qmd
        - auto: "docs/development/*"
        - section: "Code"
          href: docs/development/code/index.qmd
          contents:
            - auto: "docs/development/code/*"
        - section: "Tools"
          href: docs/development/tools/index.qmd
          contents:
            - auto: "docs/development/tools/*"
        - section: "Server"
          href: docs/development/server/index.qmd
          contents:
            - auto: "docs/development/server/*"
    - id: resources
      collapse-level: 2
      align: left
      style: "docked"
      contents:
        - docs/resources/index.qmd
        - auto: "docs/resources/*"

format:
  html:
    theme:
      light: [flatly, static/theme-light.scss]
      dark: [darkly, static/theme-dark.scss]
    css: static/styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-fold: true
    code-overflow: wrap
    code-line-numbers: false
    code-annotations: below
    highlight-style: github
    link-external-newwindow: true
    filters:
      - black-formatter
      - downloadthis
    grid:
      sidebar-width: 350px
      body-width: 1000px
      margin-width: 250px
    include-in-header: 
      - text: |
          <script 
            src="https://code.jquery.com/jquery-3.7.0.min.js" 
            integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" 
            crossorigin="anonymous">
          </script>

editor: visual
