---
version: "3.8"

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dockerfiles/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  notebook:
    container_name: notebook
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    depends_on:
      - caddy
    volumes:
      - "${PWD}/content/development/code/notebooks:/home/jovyan"
    ports:
      - "8888:8888"
    restart: unless-stopped
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

volumes:
  caddy_data:
  caddy_config:
