---
title: "Food"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, error = T)

```

---

## Sourdough Bread

Typical schedule for baking sourdough bread. Timing could change based on room temperature. 

| Time | Step | Notes |
| --- | --- | --- |
8:00am | Feed starter | Discard all but at least 2 tbsp
12:00pm | Autolyse |
1:00pm | Add starter & salt |
1:30pm | Stretch & fold | Every 30 min for 2-2.5 hours
3:30pm | Bulk rise | 1-3 hours, should rise 30-50%
8:30pm | Pre shape & bench rest | 
9:00pm | Final shaping & proof | Place in proofing baskets, cover, place in fridge overnight
9:00am | Bake | 500 F in dutch oven, 20 min lid on, lower to 450, 15-30 min lid off

## Greek Yogurt Smoothie

* Greek yogurt
* Banana
* Berries
* Oats
* Honey
* Ice

## Overnight Oats

* 90 grams oats
* 90 grams greek yogurt
* 140 grams milk
* 5 grams chia and/or flaxseed
* 15 grams honey

Stir or shake to combine. Refrigerate overnight.

## Buffalo Cauliflower

1. Preheat oven to 450 F
1. **Batter**:
    * 3/4 cup flour
    * 1 tsp paprika 
    * 2 tsp garlic powder
    * 1 tsp salt
    * 1/2 tsp black pepper 
    * 3/4 cup milk
1. **Sauce**:
    * 1/4 cup buffalo sauce
    * 1 tbsp Honey
    * 1/2 tsp black pepper
1. Split cauliflower into florets and mix in batter
1. Bake for 20 minutes, flip after 10.
1. Brush sauce onto cauliflower, bake 10 minutes.
1. Flip cauliflower and brush again with sauce, bake 10 minutes.

## Quinoa & Cucumber Salad

* **Salad**:
    * 2 cups cucumber, spiralized or julienned
    * 2 cups chopped tomatoes
    * 2 large avocados, diced
    * 1 red onion, sliced
    * 2 cups cooked quinoa
    * 1 handful chopped parsley (or cilantro)

* **Dressing** - blend the following:
    * 1 ripe avocado
    * 1/4 cup white wine vinegar
    * Juice of one lime
    * Salt and fresh cracked pepper, to taste
    * 3/4 cup olive oil
    