---
title: "Workouts"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, error = T)

# https://readxl.tidyverse.org/
library(tidyverse)
library(readxl)
library(DT)
```

---


# Routines


```{r, include=F}
workouts <- "./static/workouts.xlsx"
w1 <- read_excel(workouts, sheet=1)
w2 <- read_excel(workouts, sheet=2)
w3 <- read_excel(workouts, sheet=3)
w4 <- read_excel(workouts, sheet=4)
schedule <- read_excel(workouts, sheet=5)
```


## Option 1
The following regimen outlines a 4 week lift cycle. The routine is a slightly modified version of [this](https://jackedgorilla.com/chris-pratt-workout-routine/).

Non-lift days should be supplemented with active recovery workouts. An example 4 week cycle could look something like this:

```{r, eval=T}
datatable(schedule, options=list(scrollX=T, dom='t'), rownames=FALSE)
```

### Back, Biceps, Abs

```{r, eval=T}
datatable(w1, options=list(scrollX=T, dom='t'))
```


### Chest & Triceps

```{r, eval=T}
datatable(w2, options=list(scrollX=T, dom='t'))
```

### Legs

```{r, eval=T}
datatable(w3, options=list(scrollX=T, dom='t'))
```

### Shoulders & Traps

```{r, eval=T}
datatable(w4, options=list(scrollX=T, dom='t'))
```

