---
title: 21 Day Calisthenics
description: 21 Day Calisthenics Workout
---

## Week 1

### (1) Day 1 – Legs & Glutes

- 40 [Jumping Jacks](https://www.gymaholic.co/exercises/635/jumping-jack)
- 20 [Lunges](https://www.gymaholic.co/exercises/734/lunge)
- 25 [Squats](https://www.gymaholic.co/exercises/1260/squat)
- 10 [Star Jumps](https://www.gymaholic.co/exercises/1266/star-jump)
- 10 [Reverse Cross Lunges](https://www.gymaholic.co/exercises/332/reverse-cross-lunge)

### (1) Day 2 – Arms & Abs

- 15 [Burpees](https://www.gymaholic.co/exercises/236/burpee)
- 10 [Push Ups](https://www.gymaholic.co/exercises/888/push-up)
- 60s [Boxing Punches](https://www.youtube.com/watch?v=o9qPlLLGv6k)
- 40 [Mountain Climbers](https://www.gymaholic.co/exercises/819/mountain-climber)
- 25 [Leg Raises](https://www.gymaholic.co/exercises/766/lying-floor-leg-raise)

### (1) Day 3 – Triceps & Obliques

- 40 [Russian Twists](https://www.gymaholic.co/exercises/947/russian-twist)
- 15 [Plank-to-Push up](https://www.youtube.com/watch?v=nToxCj-QA7E)
- 15 [Bench\\Chair Dips](https://www.youtube.com/watch?v=0326dy_-CzM)
- 30-Second [Plank](https://www.gymaholic.co/exercises/858/plank)
- 40 [Crunches](https://www.youtube.com/watch?v=0t4t3IpiEao)

### (1) Day 4 – Arms & Abs

- 30 [Shoulder Taps](https://www.youtube.com/watch?v=a2duDaO9BhM)
- 25 [Leg Raises](https://www.gymaholic.co/exercises/766/lying-floor-leg-raise)
- 10 [Push Ups](https://www.gymaholic.co/exercises/888/push-up)
- 40 [Russian Twists](https://www.gymaholic.co/exercises/947/russian-twist)
- 45-Second [Plank](https://www.gymaholic.co/exercises/858/plank)

### (1) Day 5 – Total Body Workout

- 60s [Boxing Punches](https://www.youtube.com/watch?v=o9qPlLLGv6k)
- 15 [Burpees](https://www.gymaholic.co/exercises/236/burpee)
- 25 [Squats](https://www.gymaholic.co/exercises/1260/squat)
- 10 [Star Jumps](https://www.gymaholic.co/exercises/1266/star-jump)
- 40 [Mountain Climbers](https://www.gymaholic.co/exercises/819/mountain-climber)
- 10 [Push Ups](https://www.gymaholic.co/exercises/888/push-up)

## Week 2

### (2) Day 1 – Legs & Glutes

- 60s [Frankensteins](https://www.youtube.com/watch?v=m7muRa-r0LE)
- 10 [Squat Kicks](https://www.gymaholic.co/exercises/125/squat-to-alternate-leg-kickback)
- 10 [Donkey Kicks](https://www.youtube.com/watch?v=SJ1Xuz9D-ZQ) (each leg)
- 20 [Floor Bridge](https://www.youtube.com/watch?v=Z3cY3d3BBo4)
- 10 [Fire Hydrants](https://www.youtube.com/watch?v=hjMEwbXhya4) (each leg)

### (2) Day 2 – Arms & Abs

- 60s [Boxing Punches](https://www.youtube.com/watch?v=o9qPlLLGv6k)
- 10 [Close grip push ups](https://www.gymaholic.co/exercises/889/close-grip-diamond-push-up)
- 15 [Shoulder Taps](https://www.youtube.com/watch?v=a2duDaO9BhM)
- 20 [Sit ups w/ boxing punches](https://www.youtube.com/watch?v=jHWvyaGVH4s)
- 20 [V ups](https://www.youtube.com/watch?v=iP2fjvG0g3w)

### (2) Day 3 – Triceps & Obliques

- 40 [Russian Twists](https://www.gymaholic.co/exercises/947/russian-twist)
- 15 [Plank-to-Push up](https://www.youtube.com/watch?v=nToxCj-QA7E)
- 10 [Bench\\Chair Dips](https://www.youtube.com/watch?v=0326dy_-CzM)
- 30s [Side Plank](https://www.gymaholic.co/exercises/1072/side-plank) (right side)
- 30s [Side Plank](https://www.gymaholic.co/exercises/1072/side-plank) (left side)
- 30 [Heel Touches](https://www.youtube.com/watch?v=fLajmFLpJ_w)

### (2) Day 4 – Arms & Abs

- 15 [Shoulder Taps](https://www.gymaholic.co/exercises/1060/full-plank-shoulder-tap)
- 25 [Sky Touches](https://www.youtube.com/watch?v=998SuoMNSBI)
- 60s [Boxing Punches](https://www.youtube.com/watch?v=o9qPlLLGv6k)
- 40 [Crunches](https://www.youtube.com/watch?v=0t4t3IpiEao)
- 25 [Flutter Kicks](https://www.gymaholic.co/exercises/533/flutter-kick)

### (2) Day 5 – Total Body Workout

- 60s [Boxing Punches](https://www.youtube.com/watch?v=o9qPlLLGv6k)
- 15 [Burpees](https://www.gymaholic.co/exercises/236/burpee)
- 15 [Squat Kicks](https://www.gymaholic.co/exercises/125/squat-to-alternate-leg-kickback)
- 10 [Star Jumps](https://www.gymaholic.co/exercises/1266/star-jump)
- 30 [Mountain Climbers](https://www.gymaholic.co/exercises/819/mountain-climber)
- 20 [Sit up w/ boxing punches](https://www.youtube.com/watch?v=9SB8VkgXY98)

## Week 3

### (3) Day 1 – Legs & Glutes

- 60s [Frankensteins](https://www.youtube.com/watch?v=m7muRa-r0LE)
- 10 [Squat Kicks](https://www.gymaholic.co/exercises/125/squat-to-alternate-leg-kickback)
- 10 [Fire Hydrants](https://www.youtube.com/watch?v=hjMEwbXhya4) superset w/ [Donkey Kicks](https://www.youtube.com/watch?v=SJ1Xuz9D-ZQ) (each leg)
- 20 [Single leg floor bridge](https://www.youtube.com/watch?v=AVAXhy6pl7o)
- 10 [Star Jumps](https://www.gymaholic.co/exercises/1266/star-jump)

### (3) Day 2 – Arms & Abs

- 60s [Boxing Punches](https://www.youtube.com/watch?v=o9qPlLLGv6k)
- 10 [Crunches](https://www.gymaholic.co/exercises/7/crunch)
- 15 [Shoulder Taps](https://www.gymaholic.co/exercises/1060/full-plank-shoulder-tap)
- 25 [Flutter Kicks](https://www.gymaholic.co/exercises/533/flutter-kick)
- 10 [Single leg V ups](https://www.youtube.com/watch?v=RA9nGJVwtJ4) (each leg)

### (3) Day 3 – Triceps & Obliques

- 40 [Russian Twists](https://www.youtube.com/watch?v=wkD8rjkodUI&t=3s)
- 15 [Plank-to-Push up](https://www.youtube.com/watch?v=nToxCj-QA7E)
- 10 [Bench\\Chair Dips](https://www.youtube.com/watch?v=0326dy_-CzM)
- 30s [Side Plank](https://www.youtube.com/watch?v=9dNL_mtObGQ) (right side)
- 30s [Side Plank](https://www.youtube.com/watch?v=9dNL_mtObGQ) (left side)
- 30 [Heel Touches](https://www.youtube.com/watch?v=fLajmFLpJ_w)

### (3) Day 4 – Arms & Abs

- 10 [Pike Push Ups](https://www.gymaholic.co/exercises/44/pike-push-up)
- 15 [Sky Touches](https://www.youtube.com/watch?v=998SuoMNSBI)
- 60 [Boxing Punches](https://www.youtube.com/watch?v=o9qPlLLGv6k)
- 20 [Bicycle Crunches](https://www.gymaholic.co/exercises/5/air-bike)
- 10 [Heel Touches](https://www.youtube.com/watch?v=fLajmFLpJ_w)

### (3) Day 5 – Total Body Workout

- 60s [Boxing Punches](https://www.youtube.com/watch?v=o9qPlLLGv6k)
- 15 [Burpees](https://www.gymaholic.co/exercises/236/burpee)
- 15 [Squat Kicks](https://www.gymaholic.co/exercises/125/squat-to-alternate-leg-kickback)
- 10 [Push Ups](https://www.gymaholic.co/exercises/888/push-up)
- 15 [Crunches](https://www.gymaholic.co/exercises/7/crunch)
- 60s [Plank](https://www.gymaholic.co/exercises/858/plank)
