---
title: psql
---

[Cheat sheet](https://quickref.me/postgres)

```{python}
import pandas as pd

f = "../../../static/development/commands.xlsx"

t4 = pd.read_excel(f, sheet_name="psql-commands")
t4.to_html(index=False)
```

### Export table to CSV

- `\copy table TO '<path>' CSV`
- `\copy table(col1,col1) TO '<path>' CSV`
- `\copy (SELECT...) TO '<path>' CSV`
  
### Backup

Use pg_dumpall to backup all databases

`$ pg_dumpall -U postgres > all.sql`

Use pg_dump to backup a database

`$ pg_dump -d mydb -f mydb_backup.sql`

- `-a`   Dump only the data, not the schema
- `-s`   Dump only the schema, no data
- `-c`   Drop database before recreating
- `-C`   Create database before restoring
- `-t`   Dump the named table(s) only
- `-F`   Format (`c`: custom, `d`: directory, `t`: tar)

Use `pg_dump -?` to get the full list of options

### Restore

`$ psql -U user mydb < mydb_backup.sql`

#### pg_restore

`$ pg_restore -d mydb mydb_backup.sql -c`

- `-U   Specify a database user`
- `-c   Drop database before recreating`
- `-C   Create database before restoring`
- `-e   Exit if an error has encountered`
- `-F   Format (c: custom, d: directory, t: tar, p: plain text sql(default))`

Use pg_restore -? to get the full list of options
