---
title: Blackened Shrimp Bowls
description: Blackened Shrimp Bowls
categories: [Healthy,Meal]
cooktime: 30 minutes
date: 2023-11-24
---

## Ingredients

- 2 c. cooked brown rice
- 1 lb. shrimp, tails removed, peeled and deveined
- 1 1/2 tsp. cumin
- 1 tsp. paprika
- 1 tsp. garlic powder
- 1/2 tsp.onion powder
- Kosher salt
- Freshly ground black pepper
- 2 tbsp. olive oil, divided
- 1 c. fire roasted corn
- 1 red pepper, diced
- 2 tbsp. freshly chopped cilantro, plus more for garnish
- Juice of 1 lime, divided
- 1 avocado, thinly sliced

## Directions

1. Make shrimp: in a large bowl, toss shrimp with cumin, paprika, garlic powder, onion powder, and season with salt and pepper. In a large skillet over medium-high heat, heat 1 tbsp olive oil. Add shrimp and cook until opaque and charred.
2. Make corn salad: in a medium bowl combine corn, pepper, and cilantro. Add 1 tbsp olive oil, juice of half a lime, and season with salt and pepper.
3. Build bowls: divide rice between 4 bowls. Top with shrimp, corn salad, and 1/4 avocado each. Garnish with cilantro, squeeze with lime and serve.

[Source](https://www.delish.com/cooking/recipe-ideas/a19624080/blackened-shrimp-bowls-recipe/)
