---
title: Buffalo Shrimp Lettuce Wraps
description: Buffalo Shrimp Lettuce Wraps
categories: [Healthy,Meal]
cooktime: 30 minutes
date: 2023-11-24
---

## Ingredients

- 4 tbsp. butter
- 2 garlic cloves, minced
- 1/4 c. hot sauce, such as Frank's
- 1 tbsp. extra-virgin olive oil
- 1 lb. shrimp, peeled and deveined, tails removed
- Kosher salt
- Freshly ground black pepper
- 1 head romaine, leaves separated, for serving
- 1/4 red onion, finely chopped
- 1 rib celery, sliced thin
- 1/2 c. blue cheese, crumbled

## Directions

1. Make buffalo sauce: In a small saucepan over medium heat, melt butter. When melted completely, add garlic and cook until fragrant, 1 minute. Add hot sauce and stir to combine. Turn heat to low while you cook the shrimp.
2. Make shrimp: In a large skillet over medium heat, heat oil. Add shrimp and season with salt and pepper. Cook, flipping halfway, until pink and opaque on both sides, about 2 minutes per side. Turn off heat and add the buffalo sauce, tossing to coat.
3. Assemble wraps: Add a small scoop of shrimp to the center of a romaine leaf, then top with red onion, celery, and blue cheese.

[Source](https://www.delish.com/cooking/a26331032/buffalo-shrimp-lettuce-wraps-recipe/)
