---
title: Philly Cheesesteak Lettuce Wraps
description: Philly Cheesesteak Lettuce Wraps
categories: [Healthy,Meal]
cooktime: 30 minutes
date: 2023-11-24
---

## Ingredients

- 2 tbsp. vegetable oil, divided
- 1 large onion, thinly sliced
- 2 large bell peppers, thinly sliced
- 1 tsp. dried oregano
- Kosher salt
- Freshly ground black pepper
- 1 lb.
- skirt steak, thinly sliced
- 1 cup. shredded provolone
- 8 large butterhead lettuce leaves
- 1 tbsp. freshly chopped parsley

## Directions

1. In a large skillet over medium heat, heat 1 tablespoon oil. Add onion and bell peppers and season with oregano, salt, and pepper. Cook, stirring often, until vegetables are tender, about 10 minutes. Remove peppers and onions from skillet and heat remaining oil in skillet.
2. Add steak in a single layer and season with salt and pepper. Cook until steak is seared on one side, about 2 minutes. Flip and cook until the steak is seared on the second side and cooked to your liking, about 2 minutes more for medium.
3. Add onion mixture back to skillet and toss to combine. Sprinkle provolone over steak and onions then cover skillet with a tight-fitting lid and cook until the cheese has melted, about 1 minute. Remove from heat.
4. Arrange lettuce on a serving platter. Scoop steak mixture onto each piece of lettuce. Garnish with parsley and serve warm.

[Source](https://www.delish.com/cooking/recipe-ideas/recipes/a57493/no-carb-philly-cheesesteaks/)
