---
title: One-Pan Chicken And Quinoa
description: One-Pan Chicken And Quinoa
categories: [Healthy,Meal]
cooktime: 1 hours
date: 2023-11-24
---

## Ingredients

- 2 lb. (about 6) boneless, skinless chicken thighs
- 1 tsp. chili powder
- Kosher salt
- Freshly ground black pepper
- 1 tbsp. extra-virgin olive oil
- 1 small yellow onion, chopped
- 1 poblano pepper, seeded and chopped
- 3 cloves garlic, minced
- 1 tbsp. tomato paste
- 1 c. low-sodium chicken broth
- 1 (14-oz.) can fire-roasted diced tomatoes
- 1 (14-oz.) can black beans, drained and rinsed
- 1 c. frozen corn, thawed
- 1 c. dry quinoa
- 1 tsp. cumin
- 1 tsp. dried oregano
- 1/4 tsp. cayenne pepper
- Juice of 1 lime
- 1/4 c. freshly chopped cilantro
- 1 avocado, sliced, for serving
- Sour cream, for serving
- Lime wedges, for serving

## Directions

1. Season chicken thighs all over with chili powder, salt, and pepper.
2. In a large skillet over medium-high heat, heat oil. Add chicken and cook until golden, about 4 minutes per side. Remove chicken from skillet and place on a plate.
3. Reduce heat to medium and add onion and poblano pepper. Cook until soft, about 5 minutes, then add garlic and cook until fragrant, 1 minute more. Add tomato paste and stir to coat veggies.
4. Pour in broth and scrape up any bits from the bottom of pan. Add tomatoes, beans, corn, and quinoa. Stir in cumin, oregano, and cayenne and season with salt and pepper. Return thighs to skillet. Bring mixture to a boil, then reduce heat and cook, covered, 20 minutes. Remove lid and continue cooking, uncovered, until quinoa is tender and chicken is cooked through, 10 to 15 minutes more.
5. Remove chicken from skillet, then stir in cilantro and lime juice.
6. Serve quinoa with chicken, avocado, sour cream, and lime wedges.

[Source](https://www.delish.com/cooking/recipe-ideas/a39455335/one-pan-chicken-and-quinoa-recipe/
)
