---
title: Chipotle Burrito Bowl
description: Chipotle Burrito Bowl
categories: [Healthy,Meal]
cooktime: 3 hours
date: 2023-11-24
---

## Ingredients

### Chipotle Chicken

- 1/2 red onion, coarsely chopped
- 2 cloves garlic
- 1 chipotle chile in adobo, plus 2 tbsp. sauce
- 3 tbsp. vegetable oil
- Juice of 1 lime
- 1 tsp. dried oregano
- 1/2 tsp. ground cumin
- Kosher salt
- Freshly ground black pepper
- 1 lb. boneless, skinless chicken breasts

### Cilantro-Lime Rice

- 1 tbsp. unsalted butter
- 1 c. basmati rice, rinsed, drained
- 1/2 tsp. kosher salt
- Juice of 2 limes, divided
- 2 c. water
- 1 tbsp. chopped fresh cilantro

### Black Beans

- 2 tbsp. neutral oil
- 1 medium yellow onion, chopped
- 3 cloves garlic, finely chopped
- 2 (15.5-oz.) cans black beans, undrained
- 1 c. water
- 1 tsp. chipotle chile powder
- 1 tsp. dried oregano
- 1 tsp. ground cumin
- 1 bay leaf
- Kosher salt
- Freshly ground black pepper

### Corn Salsa

- 24 oz. corn, cooked
- 1 medium red onion, chopped
- 1 small jalapeño, stemmed, seeded, finely chopped
- 1/4 c. fresh cilantro, chopped
- 1 tbsp. fresh lemon juice
- 1 tbsp. fresh lime juice
- Kosher salt

## Directions

### Chicken

1. In a food processor, blend onion, garlic, chile, adobo sauce, oil, lime juice, oregano, and cumin until smooth; season with salt and pepper.
2. Transfer to a large resealable bag. Add chicken and rub all over to coat. Refrigerate at least 2 hours or up to overnight.
3. Prepare a grill for high heat; heat 5 minutes. Remove chicken from marinade and discard marinade. Grill chicken until cooked through and an instant-read thermometer inserted into thickest part registers 165°, about 8 minutes per side. Transfer to a cutting board; set aside.

### Rice

1. In a large saucepan over low heat, melt butter. Add rice, salt, and juice from 1 lime and cook, stirring, until coated, about 1 minute. Add water and bring to a boil. Cover and reduce heat to low. Cook until rice is tender, 22 to 25 minutes.
2. Fold in cilantro and top with remaining lime juice.

### Beans

1. In a large skillet over medium heat, heat oil. Cook onion, stirring occasionally, until slightly tender and just turning golden, about 5 minutes. Add garlic, and cook, stirring, until fragrant, about 1 minute more.
2. Add beans, some bean liquid, water, chile powder, oregano, cumin, and bay leaf and bring to a boil. Reduce heat to medium-low and cook, stirring occasionally, until thickened, 15 to 20 minutes; season with salt and pepper.

### Salsa

In a large bowl, toss corn, onion, jalapeño, cilantro, lemon juice, and lime juice to combine; season with salt and pepper.

### Assembly

1. Slice reserved chicken into 1" pieces.
2. Divide rice among bowls. Top with chicken, beans, corn salsa, guacamole, pico de gallo, sour cream, and cilantro. Serve with lime wedges alongside.

[Source](https://www.delish.com/cooking/a43496223/copycat-chipotle-burrito-bowl-recipe/)
