---
title: Cougar Gold Mac & Cheese
description: Rich and filling Cougar Gold mac & cheese
categories: [Meal]
cooktime: 1 hour
---

## Cougar Gold Mac & Cheese

* 6 cups water
* 2 1/2 cups pasta
* 2 tbsp butter
* 2 tbsp all-purpose flour
* 1 cup milk
* 1/3 cup heavy cream
* 1 1/2 cups Cougar Gold, grated
* 1 1/2 cups Crimson Fire, grated
* 1/2 cup ricotta
* 1/2 tbsp chicken bouillon
* ground black pepper, paprika to taste
* 1/2 cup fresh breadcrumbs (optional)

Preheat oven to 350° F.

Bring the water, salt and pasta to a rolling boil in a medium saucepan. Cook just until tender. Drain pasta, put into prepared baking dish and set aside. Meanwhile prepare the sauce. In a saucepan over medium-low heat, melt 2 tablespoons of butter. While whisking, gradually add the flour. Whisk for about 2 minutes or until golden and bubbling. Very slowly add the milk & cream, whisking constantly to avoid developing lumps. Simmer for 15 minutes until thickened (alfredo sauce consistency), stirring often to prevent mixture from burning. Remove from heat and stir in Cougar cheese, ricotta, chicken bouillon, paprika and black pepper to taste. Pour sauce onto cooked pasta (do not stir). Optionally top with breadcrumbs tossed in melted butter. Bake for 30 minutes until browned and bubbling.
