---
title: Cranberry Apple Quinoa Salad
description: Cranberry Apple Quinoa Salad
categories: [Healthy,Meal]
cooktime: 30 minutes
date: 2023-11-24
---

## Ingredients

- 1 1/2 c. water or low-sodium vegetable broth
- 3/4 c. tricolor quinoa, rinsed and drained
- 1/2 c. dried cranberries
- 1 large bunch curly kale (about 5 oz.), roughly chopped
- Kosher salt
- 2 medium unpeeled apples, such as Granny Smith or Honeycrisp, chopped
- 1/4 small red onion, thinly sliced
- 1/3 c. toasted pecans, roughly chopped
- 2 oz. crumbled feta
- 1 tbsp. Dijon mustard
- 1 tbsp. extra-virgin olive oil
- 1 tbsp. honey
- Juice of 1 lemon
- Pinch of crushed red pepper flakes
- Freshly ground black pepper

## Directions

1. **Cook Quinoa:** In a medium saucepan over high heat, bring water to a boil. Add quinoa and reduce heat to medium. Cover and simmer until water is absorbed and quinoa is softened, about 15 minutes. Remove from heat. Fluff with a fork, then add cranberries on top. Cover and let steam for 5 minutes.

2. **Prepare Kale:** Meanwhile, place kale in a large bowl; season with 1 teaspoon salt. Massage kale with your hands to combine, about 1 minute. Add quinoa, cranberries, apples, onion, pecans, and feta to kale and toss to combine.

3. **Make Dressing:** In a small bowl, whisk mustard, oil, honey, lemon juice, and red pepper flakes; season with salt and black pepper.

4. **Combine and Serve:** Pour dressing over the salad and toss to combine.

[Source](https://www.delish.com/cooking/recipe-ideas/a42028408/cranberry-apple-quinoa-salad-recipe/)
