---
title: Fish Taco Bowls
description: Fish Taco Bowls
categories: [Healthy,Meal]
cooktime: 30 minutes
date: 2023-11-24
---

## Ingredients

### Spicy Slaw

- 1 jalapeño, seeds removed, finely chopped
- 1 small clove garlic, grated
- 2 tbsp. mayonnaise
- 2 tbsp. sour cream
- Zest and juice of 1 lime
- 1 tsp. kosher salt
- 1/4 tsp. granulated sugar
- 6 c. shredded green and/or red cabbage
- 1/4 c. chopped fresh cilantro

### Spicy Crema

- 1/4 c. mayonnaise
- 1/4 c. sour cream
- 2 tbsp. sriracha
- Juice of 1/2 lime

### Fish & Assembly

- 3/4 c. all-purpose flour
- 2 tsp. chili powder
- 2 tsp. kosher salt
- 1/2 tsp. freshly ground black pepper
- 1/2 tsp. garlic powder
- 1 c. whole milk
- 1 1/2 lb. cod or any firm white fish, cut into strips about 3"-by-1 1/2"
- 1/2 c. neutral oil
- 1 head romaine, chopped
- 2 avocados, finely chopped
- 1 large mango, sliced

Fresh cilantro leaves and lime wedges, for serving

## Directions

### Slaw

In a large bowl, whisk jalapeño, garlic, mayonnaise, sour cream, lime zest, lime juice, salt, and granulated sugar. Add cabbage and cilantro and mix well to combine. Refrigerate until ready to use.

### Crema

In a small bowl, whisk mayonnaise, sour cream, sriracha, and lime juice. Refrigerate until ready to use.

### Assembly

1. In a medium bowl, mix flour, chili powder, salt, pepper, and garlic powder. Pour milk into another medium bowl. Place fish in milk.
2. In a large skillet over medium-high heat, heat oil. Lightly dredge fish in flour mixture, shaking off excess. Working in batches if needed, gently lay fish in skillet and cook until golden brown on one side, 3 to 4 minutes. Carefully turn and cook until second side is golden brown, about 2 minutes more. Transfer to a wire rack set in a baking sheet.
3. Divide romaine among bowls. Top with slaw, a few pieces of fish, avocado, mango, cilantro, and a drizzle of crema. Serve with lime wedges alongside.

[Source](https://www.delish.com/cooking/recipe-ideas/a43389828/fish-taco-bowls-recipe/)
