---
title: Kung Pao Chicken
description: Kung pao chicken
categories: [Healthy, Lunch, Dinner]
cooktime: 30 minutes
date: 2024-01-14
---

## Ingredients

* 65 g brown rice
* 3/4 cup water
* 1 tsp sesame oil
* 150 g chicken thighs
* 150 g green beans
* 1/2 garlic clove
* 1 tbsp tamari
* 3/4 tsp siracha
* 3/4 tsp honey
* 1/8 tsp cornstarch
* 10 g raw peanuts

## Directions

1. Cook rice according to package instructions or in a rice cooker.
2. Heat a cast-iron pan over medium heat and add the sesame oil. Once hot add the chicken and cook for about four to five minutes, stirring occasionally. Remove and set aside on a plate.
3. Add the green beans to the same skillet and cook for two to three minutes,until just starting to soften. Add the garlic and cook for one minute more, until fragrant. Add the chicken back in and put a lid on to finish cooking,about two to three minutes more.
4. Meanwhile, in a small bowl, mix together the tamari, sriracha, honey, and cornstarch. Remove the lid and add the sauce. Reduce the heat and stir to combine until thickened, about one minute.
5. Place the rice onto a plate and add the chicken and green beans. Top with peanuts. Enjoy!
