---
title: Garlic Butter Meatballs & Zoodles
description: Garlic Butter Meatballs & Zoodles
categories: [Healthy,Meal]
cooktime: 35 minutes
date: 2023-11-24
---

## Ingredients

- 1 lb. ground turkey
- 5 cloves garlic, minced and divided
- 1 large egg, beaten
- 1/2 c. freshly grated Parmesan, plus more for garnish
- 2 tbsp. freshly chopped parsley
- 1/4 tsp. crushed red pepper flakes
- Kosher salt
- Freshly ground black pepper
- 2 tbsp. extra-virgin olive oil
- 4 tbsp. butter
- 1 lb. zoodles
- Juice of 1/2 a lemon

## Directions

1. In a large bowl, mix ground turkey, 2 cloves garlic (2 teaspoons minced), egg, Parmesan, parsley, and red pepper flakes. Season with salt and pepper, then form into tablespoon-size meatballs.
2. In a large skillet over medium heat, heat oil and cook meatballs until golden on all sides and cooked through, about 10 minutes. Transfer to a plate and wipe out skillet with a paper towel.
3. Melt butter in skillet and add remaining minced garlic. Cook until fragrant, 1 minute. Add zoodles to skillet, toss with garlic butter, and add lemon juice. Return meatballs to skillet and heat until warmed through.
4. Garnish with Parmesan before serving.

[Source](https://www.delish.com/cooking/a22159055/garlic-butter-meatballs-recipe/)
