---
title: Spicy Cajun Shrimp with Pineapple
description: Spicy cajun shrimp with pineapple
categories: [Healthy, Lunch, Dinner]
cooktime: 40 minutes
date: 2024-01-14
---

## Ingredients

* 40 g brown rice
* 150 g shrimp
* 80 g pineapple
* 120 g red bell pepper
* 60 g red onion
* 2 tsp extra virgin olive oil
* 1 1/4 cajun seasoning
* 1/4 lime

## Directions

1. Cook rice according to package instructions or in a rice cooker.
2. Preheat the oven to 400ºF (204ºC) and line a baking sheet with parchment paper.
3. Add the shrimp, pineapple, peppers, and onions to the baking sheet and drizzle with the oil and jerk seasoning. Toss until evenly coated then arrange everything into an even layer. Bake for six to eight minutes or until theshrimp is cooked through.
4. Remove the shrimp from the baking sheet and continue to cook for six to eight minutes more until the peppers are tender.
5. Return the shrimp to the baking sheet and drizzle with the lime juice and stirto combine. Place the cooked rice and shrimp onto a plate and enjoy!
