---
title: Shrimp Fried Cauliflower Rice
description: Shrimp fried cauliflower rice
categories: [Healthy, Lunch, Dinner]
cooktime: 20 minutes
date: 2024-01-14
---

## Ingredients

* 130 g shrimp
* 1/8 tsp chili powder
* 1 tsp extra virgin olive oil
* 1 egg
* 100 g cauliflower rice
* 90 g red bell pepper
* 1 1/2 tbsp soy sauce
* 1 green onion
* 75 g brown rice

## Directions

1. Cook rice according to package instructions or in a rice cooker.
2. Season the shrimp with the chili powder and heat a skillet over medium heat. Spray with non-sticky spray and cook the shrimp for about 3 minutes perside. Remove and set aside.
3. In the same pan, add the egg and scramble. Once the egg is fully cooked, remove and set aside.
4. In the same pan, add the oil and then add the cauliflower rice and red pepper. Cook without moving the ingredients for 3 to 4 minutes, allowingthe cauliflower rice to get crispy. Then stir and cook for 5 more minutes. Add the soy sauce and stir to incorporate all ingredients together.
5. Add the shrimp, brown rice, and egg back to the pan and stir to mix everything together. Top with the green onion, and place on a separateplate. Enjoy!
