---
title: Spicy Salmon Bowl
description: Spicy Salmon Bowl
categories: [Healthy,Meal]
cooktime: 1 hours
date: 2023-11-24
---

## Ingredients

### For the salmon

- 1/3 c. low-sodium soy sauce
- 1/3 c. extra-virgin olive oil
- 1/4 c. chili garlic sauce
- Juice of 1 lime
- 2 tbsp. honey
- 4 cloves garlic, minced
- 4 (4-oz.) salmon fillets

### For the quick pickled cucumbers

- 1/2 c. rice vinegar or rice wine vinegar
- 1 tbsp. granulated sugar
- 1 tsp. kosher salt
- 2 tsp. toasted sesame oil
- 3 Persian cucumbers, thinly sliced

### For the spicy mayo

- 1/2 c. mayonnaise
- 2 tbsp. Sriracha
- 2 tsp. toasted sesame oil

### For the bowls

- Cooked brown rice
- 1 avocado, sliced
- 1 medium carrot, grated
- 1/2 red onion, thinly sliced
- Cilantro leaves, torn
- Sesame seeds

## Directions

1. **Make salmon:** Preheat oven to 350° and line a large baking sheet with foil. In a medium bowl, whisk together soy sauce, olive oil, chili garlic sauce, lime juice, honey, and garlic. Add salmon and gently toss to combine. Place on prepared baking sheet and bake until salmon is fork-tender, 20 to 25 minutes.

2. **Meanwhile, make pickled cucumbers:** In a microwave-safe bowl or jar, add vinegar, sugar, and salt and microwave until sugar and salt are dissolved, about 2 minutes. Stir in sesame oil, then add cucumbers and shake to combine. Cover with a tight-fitting lid or plastic wrap until ready to use.

3. **Make spicy mayo:** In a small bowl, combine mayonnaise, Sriracha, and sesame oil.

4. **Assemble bowls:** Divide rice among 4 bowls. Top with salmon, pickled cucumbers, avocado, carrot, red onion, cilantro, and sesame seeds. Drizzle with spicy mayo.

[Source](https://www.delish.com/cooking/recipe-ideas/a26950912/spicy-salmon-bowl-recipe/)
