---
title: Stuffed Peppers with Falafel
description: Stuffed Peppers with Falafel
categories: [Healthy,Meal]
cooktime: 45 minutes
date: 2023-11-24
---

## Ingredients

- 4 tbsp. extra-virgin olive oil, divided
- 1 large yellow onion, finely chopped
- 3 garlic cloves, minced
- kosher salt
- freshly ground black pepper
- 2 15.5-ounce cans chickpeas, drained
- 2 tsp. ground cumin
- 1 tsp. ground coriander
- 1/4 c. plus 2 tablespoons chopped curly parsley
- 4 bell peppers, halved lengthwise, seeds and ribs discarded  
- 1/4 c. finely chopped tomatoes
- 1/4 c. finely chopped cucumbers
- 1/2 lemon
- Tahini, for serving

## Directions

1. Preheat oven to 400°F. In a large skillet, heat 2 tablespoons olive oil over medium-high heat. Add onion and garlic and season with salt and pepper. Cook, stirring often, until softened, about 5 minutes. Transfer onion mixture to a bowl.
2. Add chickpeas, cumin, coriander, 1/4 cup parsley, and 1 tablespoon olive oil to bowl; season with salt and pepper and toss to combine.
3. Arrange bell peppers in a baking dish and fill with chickpea mixture. Roast until peppers are tender, about 30 minutes.  
4. Meanwhile, toss tomatoes and cucumbers with lemon juice, remaining 2 tablespoons parsley and 1 tablespoon olive oil.
5. Serve peppers topped with tomato salad and drizzled with tahini.

[Source](https://www.delish.com/cooking/recipe-ideas/a37418908/vegetarian-stuffed-peppers-recipe/)
